version: 2

updates:
  - package-ecosystem: docker
    directories:
      - services/**/*
    schedule:
      interval: cron
      cronjob: "0 6 * * 5"
      timezone: Europe/Berlin
    commit-message:
      prefix: build
    open-pull-requests-limit: 5
    rebase-strategy: disabled
    groups:
      major:
        patterns:
          - "*"
        update-types:
          - major
      python-runtime:
        patterns:
          - "python"
          - "astral-sh/uv"
          - "*astral-sh/uv*"
        update-types:
          - minor
      minor-and-patch:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: "0 6 * * 5"
      timezone: Europe/Berlin
    cooldown:
      default-days: 3
    commit-message:
      prefix: build
    open-pull-requests-limit: 5
    rebase-strategy: disabled
    groups:
      major:
        patterns:
          - "*"
        update-types:
          - major
      minor-and-patch:
        patterns:
          - "*"

  - package-ecosystem: terraform
    directories:
      - services/**/*
    schedule:
      interval: cron
      cronjob: "0 6 * * 5"
      timezone: Europe/Berlin
    cooldown:
      default-days: 3
    commit-message:
      prefix: build
    open-pull-requests-limit: 5
    rebase-strategy: disabled
    groups:
      major:
        patterns:
          - "*"
        update-types:
          - major
      minor-and-patch:
        patterns:
          - "*"

  - package-ecosystem: helm
    directories:
      - services/**/*
    schedule:
      interval: cron
      cronjob: "0 6 * * 5"
      timezone: Europe/Berlin
    cooldown:
      default-days: 3
    commit-message:
      prefix: build
    open-pull-requests-limit: 5
    rebase-strategy: disabled
    groups:
      major:
        patterns:
          - "*"
        update-types:
          - major
      minor-and-patch:
        patterns:
          - "*"
