version: '3.8'

services:
  quick-start-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORKSPACES: "@unique/mcp-server-quick-start"
    ports:
      - "51345:51345"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
