packages:
  - services/*
  - "!services/hello-mcp"
  - "!services/kb-mcp"
  - "!services/backstop-mcp"
  - "!services/office-365-mcp"
  - "!services/with-intelligence-mcp"
  - packages/*

injectWorkspacePackages: true
savePrefix: ""
