apiVersion: v2
name: hello-mcp
description: Minimal no-auth Python FastMCP hello server.
type: application
version: 0.1.1
appVersion: 0.1.1
dependencies:
  - name: base
    repository: oci://ghcr.io/unique-ag/helm
    version: 0.1.0-4c70c3
