apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.postgresql
  version: v2
  metadata:
  - name: connectionString
    value: postgres://postgres:postgres@localhost:9001/dapr