export const UNIQUE_PUBLIC_FETCH = Symbol('UNIQUE_PUBLIC_FETCH');
export const UNIQUE_PUBLIC_SDK_OPTIONS = Symbol('UNIQUE_PUBLIC_SDK_OPTIONS');
export const USER_IDENTITY_RESOLVER = Symbol('USER_IDENTITY_RESOLVER');
