# yaml-language-server: $schema=https://unpkg.com/@powersync/service-schema@latest/json-schema/powersync-config.json

telemetry:
  disable_telemetry_sharing: true

replication:
  connections:
    - type: postgresql
      uri: postgres://postgres:postgres@postgres:5432/agentic-outlook-mcp
      sslmode: disable

storage:
  type: postgresql
  uri: postgres://postgres:postgres@postgres:5432/agentic-outlook-mcp-powersync
  sslmode: disable

port: 8080

sync_rules:
  path: sync_rules.yaml

client_auth:
  jwks_uri: http://host.docker.internal:3000/.well-known/jwks.json
  audience: ["http://localhost:3000/mcp"]

api:
  tokens:
    - secret
