import { ResponseType } from '@microsoft/microsoft-graph-client';
import { Injectable, Logger } from '@nestjs/common';
import { Span, TraceService } from 'nestjs-otel';
import { GraphClientFactory } from '~/msgraph/graph-client.factory';
import { readSizedContent, type SizedContent } from '~/utils/sized-content';
import { RecordingCollection } from './transcript.dtos';

export interface RecordingData {
  id: string;
  // Opens the recording for upload as a stream paired with its byte size (Azure Blob requires a
  // known Content-Length).
  content: () => Promise<SizedContent>;
  startDateTime: Date;
  endDateTime: Date;
}

@Injectable()
export class TranscriptRecordingService {
  private readonly logger = new Logger(TranscriptRecordingService.name);

  public constructor(
    private readonly trace: TraceService,
    private readonly graphClientFactory: GraphClientFactory,
  ) {}

  /**
   * Fetch the correlated recording from MS Graph.
   * Returns the recording data if found, or null if not available.
   */
  @Span()
  public async fetchRecording(
    userProfileId: string,
    ownerPath: string,
    meetingId: string,
    contentCorrelationId: string,
  ): Promise<RecordingData | null> {
    const span = this.trace.getSpan();
    span?.setAttribute('content_correlation_id', contentCorrelationId);
    span?.setAttribute('meeting_id', meetingId);

    try {
      const client = this.graphClientFactory.createClientForUser(userProfileId);

      // Query recordings filtered by contentCorrelationId
      // contentCorrelationId is a GUID generated by MS Graph, always safe for OData filter
      const recordingsResponse = await client
        .api(`${ownerPath}/onlineMeetings/${meetingId}/recordings`)
        .filter(`contentCorrelationId eq '${contentCorrelationId}'`)
        .get();

      const recordings = await RecordingCollection.parseAsync(recordingsResponse);

      if (recordings.value.length === 0) {
        span?.addEvent('recording_not_found');
        this.logger.debug(
          { contentCorrelationId, meetingId },
          'No correlated recording found for this transcript',
        );
        return null;
      }

      // biome-ignore lint/style/noNonNullAssertion: checked above
      const recording = recordings.value[0]!;

      span?.setAttribute('recording_id', recording.id);
      this.logger.debug(
        { recordingId: recording.id },
        'Located correlated meeting recording in Microsoft Graph',
      );

      return {
        id: recording.id,
        content: async () =>
          readSizedContent(
            await client
              .api(`${ownerPath}/onlineMeetings/${meetingId}/recordings/${recording.id}/content`)
              .header('Accept', 'video/mp4')
              .responseType(ResponseType.RAW)
              .get(),
          ),
        startDateTime: recording.createdDateTime,
        endDateTime: recording.endDateTime,
      };
    } catch (error) {
      span?.addEvent('failed_to_retrieve_recording', {
        error: error instanceof Error ? error.message : String(error),
      });
      this.logger.warn({ error }, 'Failed to retrieve meeting recording from MS Graph');
      return null;
    }
  }
}
