import { Injectable, Logger } from '@nestjs/common';
import { Span, TraceService } from 'nestjs-otel';
import { GraphClientFactory } from '~/msgraph/graph-client.factory';
import { RecordingCollection } from './transcript.dtos';

export interface RecordingData {
  id: string;
  content: ReadableStream<Uint8Array<ArrayBuffer>>;
}

@Injectable()
export class TranscriptRecordingService {
  private readonly logger = new Logger(TranscriptRecordingService.name);

  public constructor(
    private readonly trace: TraceService,
    private readonly graphClientFactory: GraphClientFactory,
  ) {}

  /**
   * Fetch the correlated recording from MS Graph.
   * Returns the recording data if found, or null if not available.
   */
  @Span()
  public async fetchRecording(
    userProfileId: string,
    userId: string,
    meetingId: string,
    contentCorrelationId: string,
  ): Promise<RecordingData | null> {
    const span = this.trace.getSpan();
    span?.setAttribute('content_correlation_id', contentCorrelationId);
    span?.setAttribute('meeting_id', meetingId);

    try {
      const client = this.graphClientFactory.createClientForUser(userProfileId);

      // Query recordings filtered by contentCorrelationId
      // contentCorrelationId is a GUID generated by MS Graph, always safe for OData filter
      const recordingsResponse = await client
        .api(`/users/${userId}/onlineMeetings/${meetingId}/recordings`)
        .filter(`contentCorrelationId eq '${contentCorrelationId}'`)
        .get();

      const recordings = await RecordingCollection.parseAsync(recordingsResponse);

      if (recordings.value.length === 0) {
        span?.addEvent('recording_not_found');
        this.logger.debug(
          { contentCorrelationId, meetingId },
          'No correlated recording found for this transcript',
        );
        return null;
      }

      // biome-ignore lint/style/noNonNullAssertion: checked above
      const recording = recordings.value[0]!;

      span?.setAttribute('recording_id', recording.id);
      this.logger.debug(
        { recordingId: recording.id },
        'Located correlated meeting recording in Microsoft Graph',
      );

      // Fetch recording content (MP4 stream)
      const mp4Stream: ReadableStream<Uint8Array<ArrayBuffer>> = await client
        .api(`/users/${userId}/onlineMeetings/${meetingId}/recordings/${recording.id}/content`)
        .header('Accept', 'video/mp4')
        .getStream();

      span?.addEvent('recording_content_retrieved');
      this.logger.log(
        { recordingId: recording.id },
        'Successfully fetched recording from MS Graph',
      );

      return { id: recording.id, content: mp4Stream };
    } catch (error) {
      span?.addEvent('failed_to_retrieve_recording', {
        error: error instanceof Error ? error.message : String(error),
      });
      this.logger.warn({ error }, 'Failed to retrieve meeting recording from MS Graph');
      return null;
    }
  }
}
