{{- if .Values.mcpConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base.fullname" . }}-config
  labels:
    {{- include "base.labels.common" . | nindent 4 }}
data:
  {{- include "chart.config.app" . | nindent 2 }}
  {{- include "chart.config.delegatedAccess" . | nindent 2 }}
  {{- include "chart.config.ingestion" . | nindent 2 }}
  {{- include "chart.config.auth" . | nindent 2 }}
  {{- include "chart.config.microsoft" . | nindent 2 }}
  {{- include "chart.config.unique" . | nindent 2 }}
{{- end }}
