{{- if .Values.mcpConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- include "chart.config.app" . | nindent 2 }}
  {{- include "chart.config.auth" . | nindent 2 }}
  {{- include "chart.config.logs" . | nindent 2 }}
  {{- include "chart.config.microsoft" . | nindent 2 }}
  {{- include "chart.config.unique" . | nindent 2 }}
{{- end }}
