server:
  deployment:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
  hooks:
    migration:
      enabled: false
      command: |
        pnpm run db:migrate:deploy
  extraObjects:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: apps-mcp-server-factset-mcp
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/hostname: factset.mcp.unique.app
          konghq.com/plugins: unique-route-metrics
      spec:
        ingressClassName: kong
        tls:
          - hosts:
              - factset.mcp.unique.app
            secretName: apps-mcp-server-factset-mcp-tls
        rules:
          - host: factset.mcp.unique.app
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: apps-mcp-server-factset
                      port:
                        number: 80
  image:
    repository: ghcr.io/unique-ag/connectors/services/factset-mcp # FIXME: Naming is not consistent, must be fixed before BETA (mcp is mentioned twice, mcp/servers/xxx-mcp)
    tag: 0.2.2 # x-release-please-version
  networkPolicy:
    enabled: false # TODO: Policies must be defined as good practice, living documentation and as enterprise software and standard (ingress- and egress-policies)
  ports:
    application: 51345
    metrics: 51346
  probes:
    enabled: true
  env:
    OTEL_METRICS_EXPORTER: "prometheus"
    OTEL_EXPORTER_PROMETHEUS_PORT: "51346"
    OTEL_EXPORTER_PROMETHEUS_HOST: "0.0.0.0"
    ZITADEL_REQUIRED_ROLE: mcp.factset.write
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  volumes:
    - name: tmp
      emptyDir: {}
  volumeMounts:
    - name: tmp
      mountPath: /tmp
  prometheus:
    enabled: true
  routes:
    paths:
      default:
        enabled: false

grafana:
  dashboard:
    enabled: true
    folder: "mcp-servers"
