export const SPC_SYNC_DURATION_SECONDS = Symbol('SPC_SYNC_DURATION_SECONDS');

export const SPC_INGESTION_FILE_PROCESSED_TOTAL = Symbol('SPC_INGESTION_FILE_PROCESSED_TOTAL');

export const SPC_MS_GRAPH_API_REQUEST_DURATION_SECONDS = Symbol(
  'SPC_MS_GRAPH_API_REQUEST_DURATION_SECONDS',
);

export const SPC_MS_GRAPH_API_THROTTLE_EVENTS_TOTAL = Symbol(
  'SPC_MS_GRAPH_API_THROTTLE_EVENTS_TOTAL',
);

export const SPC_MS_GRAPH_API_SLOW_REQUESTS_TOTAL = Symbol('SPC_MS_GRAPH_API_SLOW_REQUESTS_TOTAL');

export const SPC_UNIQUE_GRAPHQL_API_REQUEST_DURATION_SECONDS = Symbol(
  'SPC_UNIQUE_GRAPHQL_API_REQUEST_DURATION_SECONDS',
);

export const SPC_UNIQUE_GRAPHQL_API_SLOW_REQUESTS_TOTAL = Symbol(
  'SPC_UNIQUE_GRAPHQL_API_SLOW_REQUESTS_TOTAL',
);

export const SPC_UNIQUE_REST_API_REQUEST_DURATION_SECONDS = Symbol(
  'SPC_UNIQUE_REST_API_REQUEST_DURATION_SECONDS',
);

export const SPC_UNIQUE_REST_API_SLOW_REQUESTS_TOTAL = Symbol(
  'SPC_UNIQUE_REST_API_SLOW_REQUESTS_TOTAL',
);

export const SPC_FILE_MOVED_TOTAL = Symbol('SPC_FILE_MOVED_TOTAL');

export const SPC_FILE_DIFF_EVENTS_TOTAL = Symbol('SPC_FILE_DIFF_EVENTS_TOTAL');

export const SPC_FILE_DELETED_TOTAL = Symbol('SPC_FILE_DELETED_TOTAL');

export const SPC_PERMISSIONS_SYNC_DURATION_SECONDS = Symbol(
  'SPC_PERMISSIONS_SYNC_DURATION_SECONDS',
);

export const SPC_PERMISSIONS_SYNC_GROUP_OPERATIONS_TOTAL = Symbol(
  'SPC_PERMISSIONS_SYNC_GROUP_OPERATIONS_TOTAL',
);

export const SPC_PERMISSIONS_SYNC_FOLDER_OPERATIONS_TOTAL = Symbol(
  'SPC_PERMISSIONS_SYNC_FOLDER_OPERATIONS_TOTAL',
);

export const SPC_PERMISSIONS_SYNC_FILE_OPERATIONS_TOTAL = Symbol(
  'SPC_PERMISSIONS_SYNC_FILE_OPERATIONS_TOTAL',
);
