server:
  hooks:
    migration:
      enabled: true
      command: |
        pnpm run db:migrate:deploy
  extraRoutes:
    # TODO: Only for MCP inspector, potentiallyremove before BETA or for production environments
    mcp:
      annotations:
        konghq.com/plugins: unique-route-metrics
        konghq.com/strip-path: "true"
      enabled: true
      matches:
        - path:
            type: PathPrefix
            value: /mcp/server/outlook
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: kong
          namespace: system
  image:
    repository: ghcr.io/unique-ag/mcp/server/outlook-mcp # FIXME: Naming is not consistent, must be fixed before BETA (mcp is mentioned twice, mcp/servers/xxx-mcp)
    tag: 0.0.4 # TODO: Tag must be auto-injected via release process from package.json
  networkPolicy:
    enabled: false # TODO: Policies must be defined as good practice, living documentation and as enterprise software and standard (ingress- and egress-policies)
  ports:
    application: 51345
  probes:
    enabled: false
  prometheus:
    enabled: false
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  volumes:
    - name: tmp
      emptyDir: {}
    - name: pnpm-virtual-store
      emptyDir: {}
  volumeMounts:
    - name: tmp
      mountPath: /tmp
  # routes: can not use since that uses the JWT middleware, see extraRoutes
