server:
  hooks:
    migration:
      enabled: true
      command: |
        pnpm run db:migrate:deploy
  extraObjects:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: apps-mcp-server-outlook-mcp
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/hostname: outlook.mcp.unique.app
          konghq.com/plugins: unique-route-metrics
      spec:
        ingressClassName: kong
        tls:
          - hosts:
              - outlook.mcp.unique.app
            secretName: apps-mcp-server-outlook-mcp-tls
        rules:
          - host: outlook.mcp.unique.app
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: apps-mcp-server-outlook
                      port:
                        number: 80
  image:
    repository: ghcr.io/unique-ag/mcp/server/outlook-mcp # FIXME: Naming is not consistent, must be fixed before BETA (mcp is mentioned twice, mcp/servers/xxx-mcp)
    tag: 0.1.0 # TODO: Tag must be auto-injected via release process from package.json
  networkPolicy:
    enabled: false # TODO: Policies must be defined as good practice, living documentation and as enterprise software and standard (ingress- and egress-policies)
  ports:
    application: 51345
  probes:
    enabled: true
  prometheus:
    enabled: false
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  volumes:
    - name: tmp
      emptyDir: {}
  volumeMounts:
    - name: tmp
      mountPath: /tmp
  # routes: can not use since that uses the JWT middleware, see extraRoutes
