apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.port }}
  selector:
    app: {{ .Release.Name }}