name: Release-Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write
    outputs:
      "services/factset-mcp--release_created": ${{ steps.release.outputs['services/factset-mcp--release_created'] }}
      "services/factset-mcp--version": ${{ steps.release.outputs['services/factset-mcp--version'] }}
      "services/outlook-mcp--release_created": ${{ steps.release.outputs['services/outlook-mcp--release_created'] }}
      "services/outlook-mcp--version": ${{ steps.release.outputs['services/outlook-mcp--version'] }}
      "services/sharepoint-connector--release_created": ${{ steps.release.outputs['services/sharepoint-connector--release_created'] }}
      "services/sharepoint-connector--version": ${{ steps.release.outputs['services/sharepoint-connector--version'] }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release

      - name: Debug release outputs
        continue-on-error: true
        run: |
          echo "Release outputs: ${{ toJson(steps.release.outputs) }}"

  release-factset-mcp:
    needs: release-please
    if: ${{ needs.release-please.outputs['services/factset-mcp--release_created'] == 'true' }}
    uses: ./.github/workflows/_template-cd.yaml
    with:
      service-name: factset-mcp
      service-version: ${{ needs.release-please.outputs['services/factset-mcp--version'] }}

  release-outlook-mcp:
    needs: release-please
    if: ${{ needs.release-please.outputs['services/outlook-mcp--release_created'] == 'true' }}
    uses: ./.github/workflows/_template-cd.yaml
    with:
      service-name: outlook-mcp
      service-version: ${{ needs.release-please.outputs['services/outlook-mcp--version'] }}
      dockerfile: services/outlook-mcp/deploy/Dockerfile

  release-sharepoint-connector:
    needs: release-please
    if: ${{ needs.release-please.outputs['services/sharepoint-connector--release_created'] == 'true' }}
    uses: ./.github/workflows/_template-cd.yaml
    with:
      service-name: sharepoint-connector
      service-version: ${{ needs.release-please.outputs['services/sharepoint-connector--version'] }}
