name: "[TEMPLATE] MCP Server CD"

on:
  workflow_call:
    inputs:
      server-name:
        description: "Name of the MCP server (e.g., factset, outlook)"
        required: true
        type: string
      server-path:
        description: "Path to the server directory (e.g., servers/factset-mcp)"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
    env:
      SERVER_PATH: ${{ inputs.server-path }}
      CHART_REPO: ghcr.io/unique-ag/mcp/server/${{ inputs.server-name }}-mcp
      GHA_CACHE_SCOPE: ${{ inputs.server-name }}-mcp
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - id: version
        run: |
          VERSION=$(jq -r '.version' "${{ env.SERVER_PATH }}/package.json")
          echo "content=$VERSION" >> $GITHUB_OUTPUT
      - id: pnpm-version
        run: |
          PNPM_VERSION=$(jq -r '.packageManager | split("@")[1]' package.json)
          echo "version=$PNPM_VERSION" >> $GITHUB_OUTPUT
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CHART_REPO }}
          tags: |
            type=raw,value=${{ steps.version.outputs.content }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          provenance: false
          cache-from: |
            type=gha,scope=${{ env.GHA_CACHE_SCOPE }}
            type=registry,ref=${{ env.CHART_REPO }}:cache
          cache-to: |
            type=registry,ref=${{ env.CHART_REPO }}:cache,mode=min
          build-args: |
            APP_NAME=${{ inputs.server-name }}-mcp
            PNPM_VERSION=${{ steps.pnpm-version.outputs.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
