name: "[TEMPLATE] MCP Server Cache Warming"

on:
  workflow_call:
    inputs:
      server-name:
        description: "Name of the MCP server (e.g., factset, outlook)"
        required: true
        type: string
      server-path:
        description: "Path to the server directory (e.g., servers/factset-mcp)"
        required: true
        type: string

permissions:
  contents: read
  packages: read
  actions: read

env:
  SERVER_PATH: ${{ inputs.server-path }}
  CHART_REPO: ghcr.io/unique-ag/mcp/server/${{ inputs.server-name }}-mcp
  GHA_CACHE_SCOPE: ${{ inputs.server-name }}-mcp

jobs:
  warm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Extract PNPM version from package.json
        id: pnpm-version
        run: |
          PNPM_VERSION=$(jq -r '.packageManager | split("@")[1]' package.json)
          echo "version=$PNPM_VERSION" >> $GITHUB_OUTPUT

      - name: Skip if no changes in last 3 days under ${{ inputs.server-path }}
        run: |
          if ! git log --since="3 days ago" --name-only --pretty=format: | grep -q '^${{ inputs.server-path }}/'; then
            echo "No recent changes; skipping warm."
            exit 0
          fi

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-warm GHA cache (no push)
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: .
          platforms: linux/amd64
          push: false
          provenance: false

          cache-from: |
            type=gha,scope=${{ env.GHA_CACHE_SCOPE }}
            type=registry,ref=${{ env.CHART_REPO }}:cache

          cache-to: |
            type=gha,scope=${{ env.GHA_CACHE_SCOPE }},mode=max,ignore-error=true

          build-args: |
            APP_NAME=${{ inputs.server-name }}-mcp
            PNPM_VERSION=${{ steps.pnpm-version.outputs.version }}
