name: "[mcp/server/factset] Publish"

on:
  push:
    branches:
      - main
    paths:
      - servers/factset-mcp/**
      - .github/workflows/factset.server.mcp.cd.yaml
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
    env:
      SERVER_PATH: servers/factset-mcp
      CHART_REPO: ghcr.io/unique-ag/mcp/server/factset-mcp
      GHA_CACHE_SCOPE: factset-mcp
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - id: version
        run: |
          VERSION=$(jq -r '.version' "${{ env.SERVER_PATH }}/package.json")
          echo "content=$VERSION" >> $GITHUB_OUTPUT
      - id: pnpm-version
        run: |
          PNPM_VERSION=$(jq -r '.packageManager | split("@")[1]' package.json)
          echo "version=$PNPM_VERSION" >> $GITHUB_OUTPUT
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CHART_REPO }}
          tags: |
            type=raw,value=${{ steps.version.outputs.content }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          provenance: false
          cache-from: |
            type=gha,scope=${{ env.GHA_CACHE_SCOPE }}
            type=registry,ref=${{ env.CHART_REPO }}:cache
          cache-to: |
            type=registry,ref=${{ env.CHART_REPO }}:cache,mode=min
          build-args: |
            APP_NAME=factset-mcp
            PNPM_VERSION=${{ steps.pnpm-version.outputs.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}