name: "[mcp/server/factset] Publish"

on:
  push:
    branches:
      - main
    paths:
      - services/factset-mcp/**
      - .github/workflows/factset.server.mcp.cd.yaml
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/_template-mcp-cd.yaml
    with:
      service-name: factset
      service-path: services/factset-mcp