name: "[mcp/server/factset] Validate"

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/services/factset-mcp/**"
      - .github/workflows/factset.server.mcp.ci.yaml

jobs:
  validate:
    uses: ./.github/workflows/_template-ci.yaml
    with:
      service-name: factset-mcp
      service-path: services/factset-mcp
