name: "[mcp/server/outlook] Warm Docker Build Cache (nightly)"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  warm:
    uses: ./.github/workflows/_template-mcp-cache.yaml
    with:
      server-name: outlook
      server-path: servers/outlook-mcp