name: "[mcp/server/outlook] Publish"

on:
  push:
    branches:
      - main
    paths:
      - servers/outlook-mcp/**
      - .github/workflows/outlook.server.mcp.cd.yaml
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/_template-mcp-cd.yaml
    with:
      server-name: outlook
      server-path: servers/outlook-mcp