on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Releases

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      # You need to explicitly output the tag name and release_created for each package
      # This assumes your release-please-config.json and .release-please-manifest.json
      # are set up to handle multiple packages and will output these.
      "services/outlook-mcp--tag_name": ${{ steps.release.outputs['services/outlook-mcp--tag_name'] }}
      "services/outlook-mcp--release_created": ${{ steps.release.outputs['services/outlook-mcp--release_created'] }}
      # Add more outputs for other packages here

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"

  release-outlook-mcp:
    if: ${{ needs.release-please.outputs['services/outlook-mcp--release_created'] == 'true' }}
    uses: ./.github/workflows/_template-release.yaml
    needs: release-please
    with:
      service-name: "@unique-ag/outlook-mcp"
      service-path: services/outlook-mcp
      service-tag: ${{ needs.release-please.outputs['services/outlook-mcp--tag_name'] }}
